import type { TeamMember } from "@shared/schema";

const now = new Date();

export const fallbackTeamMembers: TeamMember[] = [
  {
    id: 1,
    name: "Shivam Wadhwa",
    title: "Managing Partner",
    specialization: "Dispute Resolution",
    bio: "Leads complex disputes strategy and oversees bespoke solutions for high-stakes matters across forums.",
    email: "delhi@wadhwalawgroup.com",
    phone: "91-11-45040303",
    imageUrl: null,
    linkedIn: "https://www.linkedin.com/company/wadhwalawgroup",
    practiceAreas: ["Dispute Resolution", "Litigation"],
    education: [],
    displayOrder: 1,
    isPartner: true,
    createdAt: now,
  },
  {
    id: 2,
    name: "Tushti Wadhwa",
    title: "Partner",
    specialization: "Corporate & Commercial",
    bio: "Advises on commercial arrangements, transactions, and governance with a focus on risk-balanced execution.",
    email: "delhi@wadhwalawgroup.com",
    phone: "91-11-45040303",
    imageUrl: null,
    linkedIn: "https://www.linkedin.com/company/wadhwalawgroup",
    practiceAreas: ["Commercial", "Corporate", "Capital Markets"],
    education: [],
    displayOrder: 2,
    isPartner: true,
    createdAt: now,
  },
  {
    id: 3,
    name: "Paras Malik",
    title: "Associate Partner",
    specialization: "Banking & Finance",
    bio: "Represents lenders and borrowers on financing, restructuring, and enforcement mandates.",
    email: "delhi@wadhwalawgroup.com",
    phone: "91-11-45040303",
    imageUrl: null,
    linkedIn: "https://www.linkedin.com/company/wadhwalawgroup",
    practiceAreas: ["Banking & Finance", "Taxation and Finance"],
    education: [],
    displayOrder: 3,
    isPartner: true,
    createdAt: now,
  },
  {
    id: 4,
    name: "Khushboo Garg",
    title: "Associate Partner",
    specialization: "Real Estate & Property",
    bio: "Handles title diligence, property transactions, and contentious property matters across Delhi NCR.",
    email: "delhi@wadhwalawgroup.com",
    phone: "91-11-45040303",
    imageUrl: null,
    linkedIn: "https://www.linkedin.com/company/wadhwalawgroup",
    practiceAreas: ["Real Estate and Property Law", "Property"],
    education: [],
    displayOrder: 4,
    isPartner: true,
    createdAt: now,
  },
];
